# Domain Names
# This is the domain you will access PCF with, for example: pcf.example.com.  A hosted zone will be created for this domain.
pcf_domain: CHANGEME
# PKS Domain, this needs to be a subdomain of pcf_domain
pks_domain: CHANGEME

# GCP project to create the infrastructure in
gcp_project_id: CHANGEME

# GCP region
gcp_region: us-central1

# Identifier to prepend to GCP infrastructure names/labels; this should be globally unique
gcp_resource_prefix: CHANGEME

# GCP credentials JSON. The service account must have the Editor role.
gcp_service_account_key: |
  CHANGEME

# GCP Interopable storage access key: https://console.cloud.google.com/storage/settings
gcp_storage_access_key: CHANGEME
gcp_storage_secret_key: CHANGEME

# Storage Location
gcp_storage_bucket_location: US

# GCP Zones
gcp_zone_1: us-central1-a
gcp_zone_2: us-central1-b
gcp_zone_3: us-central1-c

# Operations Manager credentials to set
# opsman_admin_username/opsman_admin_password needs to be specified
opsman_admin_username: CHANGEME
opsman_admin_password: CHANGEME

# # The domain to access Operations Manager;
opsman_domain_or_ip_address: CHANGEME #This must be your pcf_ert_domain with "opsman." as a prefix. For example, opsman.pcf.example.com

# PCF Ops Manager minor version to track
opsman_major_minor_version: ^2\.1\.[0-9]+$ # Ops Manager minor version to track (e.g ^2\.1\.[0-9]+$ will track 2.0.x versions)

# Optional PEM-encoded certificates to add to BOSH director
opsman_trusted_certs: |

# Pivnet token for downloading resources from Pivnet. Find this token at https://network.pivotal.io/users/dashboard/edit-profile
pivnet_token: CHANGEME

# Optional. If blank the cert(s) will be generated:
pks_ssl_name1:
pks_ssl_cert1:
pks_ssl_key1:

terraform_statefile_bucket: CHANGEME
